version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173" # Change from 3000 to 5173
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "run", "dev"]
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on: []
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "run", "dev"]
    environment:
      - MONGO_URI=mongodb+srv://redophile:redophile@cluster0.1g08v.mongodb.net/mydatabase?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=dnkdsjvnjsdbvvsdkj
      - NODE_ENV=development

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
